const products = [
  {
    _id: '1',
    photo: './Images/Products/1.webp',
    productName: 'Disinfectant Spray 75% Sanitizer (500ml',
    price: 400,
    discountPercent: 11,
    noofReviews: 44,
    noofstars: 3,
  },
  {
    _id: '2',
    photo: './Images/Products/2.webp',
    productName: 'Baidyanath Chawanprash Immunity Booster 1 Kg',
    price: 545,
    discountPercent: 16,
    noofReviews: 1,
    noofstars: 4.5,
  },
  {
    _id: '3',
    photo: './Images/Products/3.webp',
    productName: 'Hyvest Ultra Matic Detergent 200 Gm',
    price: 270,
    discountPercent: 16,
    noofReviews: 1,
    noofstars: 4,
  },
  {
    _id: '4',
    photo: './Images/Products/4.webp',
    productName: 'Dabur Anmol Pure Coconut Oil(500ml)',
    price: 240,
    noofReviews: 6,
    noofstars: 1.5,
  },
  {
    _id: '5',
    photo: './Images/Products/5.webp',
    productName: 'Diamond Cool Mist Humidifiers Essential Oil...',
    price: 1345,
    noofReviews: 1,
    discountPercent: 33,
    noofstars: 3,
  },

  {
    _id: '6',
    photo: './Images/Products/6.webp',
    productName: 'Diamond Cool Mist Humidifiers Essential Oil...',
    price: 1345,
    noofReviews: 1,
    discountPercent: 33,
    noofstars: 3,
  },

  {
    _id: '7',
    photo: './Images/Products/7.webp',
    productName: 'Diamond Cool Mist Humidifiers Essential Oil...',
    price: 1345,
    noofReviews: 1,
    discountPercent: 33,
    noofstars: 3,
  },
  {
    _id: '8',
    photo: './Images/Products/1.webp',
    productName: 'Disinfectant Spray 75% Sanitizer (500ml',
    price: 400,
    discountPercent: 11,
    noofReviews: 44,
    noofstars: 3,
  },
  {
    _id: '9',
    photo: './Images/Products/2.webp',
    productName: 'Baidyanath Chawanprash Immunity Booster 1 Kg',
    price: 545,
    discountPercent: 16,
    noofReviews: 1,
    noofstars: 4,
  },
  {
    _id: '10',
    photo: './Images/Products/3.webp',
    productName: 'Hyvest Ultra Matic Detergent 200 Gm',
    price: 270,
    discountPercent: 16,
    noofReviews: 1,
    noofstars: 4,
  },
  {
    _id: '11',
    photo: './Images/Products/4.webp',
    productName: 'Dabur Anmol Pure Coconut Oil(500ml)',
    price: 240,
    noofReviews: 6,
    noofstars: 5,
  },
  {
    _id: '12',
    photo: './Images/Products/5.webp',
    productName: 'Diamond Cool Mist Humidifiers Essential Oil...',
    price: 1345,
    noofReviews: 1,
    discountPercent: 33,
    noofstars: 3,
  },

  {
    _id: '13',
    photo: './Images/Products/6.webp',
    productName: 'Diamond Cool Mist Humidifiers Essential Oil...',
    price: 1345,
    noofReviews: 1,
    discountPercent: 33,
    noofstars: 3,
  },

  {
    _id: '14',
    photo: './Images/Products/7.webp',
    productName: 'Diamond Cool Mist Humidifiers Essential Oil...',
    price: 1345,
    noofReviews: 1,
    discountPercent: 33,
    noofstars: 3,
  },
  {
    _id: '15',
    photo: './Images/Products/5.webp',
    productName: 'Diamond Cool Mist Humidifiers Essential Oil...',
    price: 1345,
    noofReviews: 1,
    discountPercent: 33,
    noofstars: 3,
  },

  {
    _id: '16',
    photo: './Images/Products/6.webp',
    productName: 'Diamond Cool Mist Humidifiers Essential Oil...',
    price: 1345,
    noofReviews: 1,
    discountPercent: 33,
    noofstars: 3,
  },

  {
    _id: '17',
    photo: './Images/Products/7.webp',
    productName: 'Diamond Cool Mist Humidifiers Essential Oil...',
    price: 1345,
    noofReviews: 1,
    discountPercent: 33,
    noofstars: 3,
  },
  {
    _id: '18',
    photo: './Images/Products/7.webp',
    productName: 'Diamond Cool Mist Humidifiers Essential Oil...',
    price: 1345,
    noofReviews: 1,
    discountPercent: 33,
    noofstars: 3,
  },
]
export default products
